Update dendron.topic.graph-view.md
dendronhq/dendron-template pull request #12
Opened 2020-09-11 10:07 UTC by ens100

Correcting a couple of typos and addition of key strokes.

2020-09-11 15:06 UTC, kevinslin commented on vault/dendron.topic.graph-view.md
> +Ctrl + Shift + P: `> Dendron: Show Note Graph`
this is different depending on os. i would say 'launch the command bar' with a link to [this](https://www.dendron.so/notes/401c5889-20ae-4b3a-8468-269def4b4865.html#launch-the-command-bar)

2020-09-11 15:07 UTC, kevinslin commented on vault/dendron.topic.graph-view.md
> +Ctrl + Shift + P: `> Dendron: Show Schema Graph`
same comment as above

2020-09-11 15:07 UTC, kevinslin requested changes
content is good, can you update the reference for keyboard shortcuts so its not windows specific?

2020-09-11 17:49 UTC, ens100 commented
I think I have submitted a revised file based on your comments but not sure if I did this correctly (still trying to get my head around GitHub)

2020-09-12 03:44 UTC, merged

2020-09-12 03:45 UTC, kevinslin commented
all good. just merged the changes. thanks for the corrections 👍